import {Raleway } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
// import HeroSection from "./_components/HeroSection";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <div className="md:px-5">
        <Header/>
        {children}
        </div>
        </body>
    </html>
  );
}
